name: SAST
on:
  workflow_dispatch:
  workflow_call:
  pull_request: 

jobs:
  semgrep_actions: 
    permissions: write-all
    name: Semgrep 
    runs-on: ubuntu-latest 
    container:
      image: eturntocorp/semgrep
    steps:
      - name: checkcode 
        uses: actions/checkout@v3 
      
      - name: scancode 
        run: semgrep scan --sarif --sarif-output=semgrep.sarif --error 
      
      - name: Run semgrep analysis (blocking mode)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
